app/account/urls.py
# app/account/urls.py

# Django & third parties modules 
from django.shortcuts import render
from django.urls import path

# Locals
from app.account import views 

# Create your urls here.

app_name = 'account'

urlpatterns = [
    path('register', views.register_view, name='register'),
]

app/personal/urls.py
# app/personal/urls.py

# Django & third parties modules 
from django.shortcuts import render
from django.urls import path

# Locals
from app.personal import views 

# Create your urls here.

app_name = 'personal'

urlpatterns = [
    path('', views.home_screen_view, name='home'),
]

config/urls.py
# config/urls.py

# Django & third parties modules 
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include 

# Locals
# from app.personal.views import (
#     home_screen_view
# )

urlpatterns = [
    
    # account
    path('', include('app.account.urls', namespace='account')),
    
    # personal
    path('', include('app.personal.urls', namespace='personal')),

    # admin
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/account/models.py
# app/account/models.py

# Django & third party modules
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

# Locals

# Create your models here.

class MyAccountManager(BaseUserManager):

	def create_user(self, email, username, password=None):
		if not email:
			raise ValueError('Users must have an email address.')
		if not username:
			raise ValueError('Users must have a username.')

		user = self.model(
			email=self.normalize_email(email),
			username=username,
		)

		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_superuser(self, email, username, password):
		user = self.create_user(
			email=self.normalize_email(email),
			password=password,
			username=username,
		)
		user.is_admin = True
		user.is_staff = True
		user.is_superuser = True
		user.save(using=self._db)
		return user

def get_profile_image_filepath(self, filename):
	"""Defining image path for each user"""
	return 'profile_images/' + str(self.pk) + '/profile_image.png'

def get_default_profile_image():
	"""Defining default image path in case user has no image"""
	return "images/logo_1080_1080.png"


# MODEL:Account
class Account(AbstractBaseUser):
	"""Defining user management in the system"""

	"""Defining user creaentials"""
	email 			= models.EmailField(verbose_name="email", max_length=60, unique=True)
	username 		= models.CharField(max_length=30, unique=True)
	date_joined		= models.DateTimeField(verbose_name='date joined', auto_now_add=True)
	last_login		= models.DateTimeField(verbose_name='last login', auto_now=True)
	is_admin		= models.BooleanField(default=False)
	is_active		= models.BooleanField(default=True)
	is_staff		= models.BooleanField(default=False)
	is_superuser	= models.BooleanField(default=False)
	profile_image	= models.ImageField(max_length=255, 
						upload_to=get_profile_image_filepath, 
						null=True, 
						blank=True, 
						default=get_default_profile_image)
	# Hiding the user's email from other users
	hide_email		= models.BooleanField(default=True)

	# Email and Username are required to create account
	# User must use its email to login
	USERNAME_FIELD = 'email' # Refer to email in line 26
	REQUIRED_FIELDS = ['username'] # Refer to username in line 27

	objects = MyAccountManager()
	
	def __str__(self):
		return self.username

	# Get profile image of the user from the:get_profile_image_filepath
	def get_profile_image_filename(self):
		return str(self.profile_image)[str(self.profile_image).index('profile_images/' + str(self.pk) + "/"):]

	# For checking permissions. to keep it simple all admin have ALL permissons
	def has_perm(self, perm, obj=None):
		return self.is_admin

	# Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
	def has_module_perms(self, app_label):
		return True

app/account/forms.py
# app/account/forms.py

# Django & third parties modules 
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from app.account.models import Account


class RegistrationForm(UserCreationForm):

	# Add email field to the form (by default UserCreationForm has no email field)
	email = forms.EmailField(
			max_length=254, 
			help_text='Required. Add a valid email address.')

	# Use Account models fields and fields in the UserCreationForm in the form
	class Meta:
		model = Account
		fields = ('email', 'username', 'password1', 'password2')

	# Check and clean the emsil if user submit the form
	def clean_email(self):
		# Get email from the form input with attribute name="email"
		email = self.cleaned_data['email'].lower()
		try:
			account = Account.objects.get(email=email)
		except Exception as e:
			return email
			
		raise forms.ValidationError(f"Email {email} is already in use.")

	# Check and clean the username if user submit the form
	def clean_username(self):
		# Get username from the form input with attribute name="username"
		username = self.cleaned_data['username']
		try:
			account = Account.objects.get(username=username)
		except Exception as e:
			return username

		raise forms.ValidationError(f"Username {username} is already in use.")

app/account/views.py
# app/account/views.py

# Django & third parties modules 
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, authenticate

# Locals
from app.account.forms import RegistrationForm

# Create your views here.

def register_view(request, *args, **kwargs):

	"""Remain the authenticated user (already logged in user), 
	if he/she try to access the register form with the HttpResponse text
	that is 'You are already authenticated as {user.email}.' """
	user = request.user 
	if user.is_authenticated:
		return HttpResponse(f"You are already authenticated as {user.email}.")
	context = {}

	# If register form is submited
	if request.POST:

		# Get all the paramters form the register form fields
		form = RegistrationForm(request.POST)
		
		# Create the user an account (save the parameters)
		# if all parameters (form) is valid
		if form.is_valid():
			form.save()

			# Because account has been created, login the user
			email = form.cleaned_data.get('email').lower()
			raw_password = form.cleaned_data.get('password1')
			account = authenticate(email=email,password=raw_password)
			login(request,account)
			destination = kwargs.get("next")
			if destination:
				return redirect(destination)
			return redirect("personal:home")

		# If form is not valid, return the form
		else:
			context['registration_form'] = form 

	return render(request, 'account/register.html', context)

app/personal/views.py
# app/personal/views.py

# Django & third parties modules 
from django.shortcuts import render

# Locals

# Create your views here.

def home_screen_view(request, *args, **kwargs):
	context = {}
	return render(request, 'personal/home.html', context)

app/personal/templates/personal/home.html
{% extends 'base.html' %}
{% block title %} Home {% endblock title %}
{% load static %}

{% block content %}

	<div>Home</div>

{% endblock content %}

templates/app/personal/index.html
{% extends 'base.html' %}
{% block title %} Home {% endblock title %}
{% load static %}

{% block content %}

	<h1>Hello World!</h1>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %} {{ block.super} }{% endblock title %}| CHAT ROOM</title>
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
	<link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
</head>
<body>	

	<!-- Header -->
	{% include 'snippets/header.html' %}
	{% include 'snippets/base_css.html' %}
	{% include 'snippets/base_js.html' %}

	<style type="text/css">
		.main{
			min-height: 100vh;
			height: 100%;
			background: #8195A7;
		}
	</style>

	<!-- Content -->
	<div class="main">
		{% block content %}

		{% endblock content %}
	</div>

	<!-- Footer -->
	{% include 'snippets/footer.html' %}

	<script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
	<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

templates/snippets/footer.html
<style type="text/css">
	.footer{
		min-height: 100px;
	}
</style>

<!-- Footer -->

<div class="d-flex flex-row align-items-center footer bg-white shadow-lg mt-4">
	<p class="m-auto">CODEWITH<span style="color:red;">ING</span> | 2023</p>
</div>
<!-- End Footer -->

templates/snippets/header.html
{% load static %}
{% block content %}

<div class="d-flex flex-column flex-lg-row p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
	<!-- MEDIUM+ screen -->
	<div class="d-none d-lg-flex flex-row my-auto flex-grow-1 align-items-center">

		<!-- col1 -->
		<h5 class="mr-3 font-weight-normal justify-content-start">
			<a class="p-2 text-dark" href="{% url 'personal:home' %}">Home</a>
		</h5>

		<!-- col2 -->
		<form class="search-bar justify-content-start">
	  		<input 
	  			type="text" 
	  			class="form-control" 
	  			name="q" 
	  			id="id_q" 
	  			placeholder="Search...">
	  	</form>

	  	<!-- col3 -->
	  	<div class="d-flex flex-row-reverse flex-grow-1">
	  		<nav class="">
				{% if request.user.is_authenticated %}
					<div class="dropdown dropleft show p-2">
						<div class="d-flex flex-row">

							<!-- Chat notifications -->
							<div class="btn-group dropleft">
								<div class="d-flex notification-icon-container rounded-circle align-items-center" id="id_chat_notification_toggle" data-toggle="dropdown">
									<span id="id_chat_notifications_count" class="notify-badge"></span>
									<span class="d-flex material-icons notifications-material-icon m-auto align-items-center">chat</span>
									<div class="dropdown-menu scrollable-menu" aria-labelledby="id_chat_notification_dropdown_toggle" id="id_chat_notifications_container"> </div>
								</div>
							</div>

							<!-- General notifications -->
							<div class="btn-group dropleft">
								<div class="d-flex notification-icon-container rounded-circle align-items-center" id="id_notification_dropdown_toggle" data-toggle="dropdown">
									<span id="id_general_notifications_count" class="notify-badge"></span>
									<span class="d-flex material-icons notifications-material-icon m-auto align-items-center">notifications</span>
									<div class="dropdown-menu scrollable-menu" aria-labelledby="id_chat_notification_dropdown_toggle" id="id_general_notifications_container"> </div>
								</div>
							</div>

							<!-- Account -->
							<div class="btn-group dropleft">
								<img class="account-image rounded-circle m-auto d-block dropdown-toggle" id="id_profile_links" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="{{ request.user.profile_image.url }}" alt="Chatroom logo" width="40" height="40">
								<div class="dropdown-menu" aria-labelledby="id_profile_links">
									<a class="dropdown-item" href="">Account</a>
									<a class="dropdown-item" href="">Logout</a>
								</div>
							</div>
						</div>
					</div>
				{% else %}
					<a class="p-2 text-dark" href="">Login</a>
					<a class="btn btn-outline-primary" href="{% url 'account:register' %}">Register</a>
				{% endif %}	
	  		</nav>
	  	</div>
	</div>

	<!-- SMALL+ screen -->
	<div class="d-flex d-md-none flex-column my-auto align-items-center">

		<!-- row 1 -->
		<h5 class="mr-3 font-weight-normal">
			<a class="p-2 text-dark" href="{% url 'personal:home' %}">Home</a>
		</h5>

		<!-- row 2 -->
		<form class="search-bar justify-content-start">
	  		<input 
	  			type="text" 
	  			class="form-control" 
	  			name="q" 
	  			id="id_q_small" 
	  			placeholder="Search...">
	  	</form>

		<!-- row 3 -->
		<div class="d-flex flex-row-reverse flex-grow-1">
	  		<nav class="">
				{% if request.user.is_authenticated %}
					<div class="dropdown dropleft p-2 mt-2">
						<div class="d-flex flex-row">

							<!-- Account -->
							<div class="btn-group dropleft">
								<img class="account-image rounded-circle m-auto d-block dropdown-toggle" id="id_profile_links" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="{{ request.user.profile_image.url }}" alt="Chatroom logo" width="40" height="40">
								<div class="dropdown-menu" aria-labelledby="id_profile_links">
									<a class="dropdown-item" href="">Account</a>
									<a class="dropdown-item" href="">Logout</a>
								</div>
							</div>
						</div>
					</div>
				{% else %}
					<a class="p-2 text-dark" href="">Login</a>
					<a class="btn btn-outline-primary mt-3" href="">Register</a>
				{% endif %}	
	  		</nav>
	  	</div>
	</div>
</div>


{% endblock content %}

templates/snippets/header_ori.html
{% load static %}
{% block content %}

<style type="text/css">
	@media (min-width: 768px) {
	  html {
	    font-size: 16px;
	  }
	}

	.search-bar{
		max-width: 500px;
		width: 100%;
	}

	form{
		width: 100%;
	}

</style>

<!-- Header -->
<div class="d-flex p-3 px-md-4 mb-4 bg-white border-bottom shadow-sm">

	<!-- LARGE SCREENS -->
	<div class="d-none d-lg-flex flex-row my-auto flex-grow-1 align-items-center">
		<h5 class="mr-3 font-weight-normal justify-content-start">
			{% if request.user.is_authenticated %}
				<a class="p-2 text-dark" href="#">show pic</a>
			{% endif %}
		</h5>
		<form class="search-bar justify-content-start" onsubmit="return executeQuery();">
	  		<input type="text" class="form-control" name="q" id="id_q" placeholder="Search...">
	  	</form>

	  	<div class="d-flex flex-row-reverse flex-grow-1">
			<nav class="">
				{% if request.user.is_authenticated %}
					<a class="p-2 text-dark" href="">Home</a>
					<a class="p-2 text-dark" href="">Logout</a>
				{% else %}
					<a class="p-2 text-dark" href="">Home</a>
					<a class="p-2 text-dark" href="">Login</a>
					<a class="btn btn-outline-primary" href="">Register</a>
				{% endif %}	
			</nav>
	  	</div>
	</div>
	<!-- END LARGE SCREENS -->

	<!-- SMALL SCREENS -->
	<div class="d-flex d-lg-none flex-column my-auto align-items-center">
		<h5 class="mr-3 font-weight-normal">
		{% if request.user.is_authenticated %}
		<a class="p-2 text-dark" href="">show pic</a>
		{% endif %}
		</h5>
		<form class="search-bar flex-grow-1" onsubmit="return executeQuery();">
		<input type="text" class="form-control" name="q" id="id_q" placeholder="Search...">
		</form>
		<div class="flex-grow-1">
			<nav class="">
				{% if request.user.is_authenticated %}
					<a class="p-2 text-dark" href="">Home</a>
					<a class="p-2 text-dark" href="">Logout</a>
				{% else %}
					<a class="p-2 text-dark" href="">Home</a>
					<a class="p-2 text-dark" href="">Login</a>
					<a class="btn btn-outline-primary" href="">Register</a>
				{% endif %}	
			</nav>
	  	</div>
	</div>
	<!-- END SMALL SCREENS -->
</div>

<script type="text/javascript">
	document.getElementById("id_q").value = "{{query}}"
</script>
<script>
function executeQuery() {
    var query = document.getElementById('id_q').value;
    window.location.replace("{{BASE_URL}}/?q=" + query)
    // "https://open-api.xyz/?q=" + query;
    return false
}

</script>
<!-- End Header -->

{% endblock content %}